[package]
authors = ["Jorge Aparicio <jorge@japaric.io>", "Hideki Sekine <sekineh@me.com>"]
categories = ["embedded", "no-std"]
description = "Minimal runtime / startup for Cortex-M microcontrollers"
documentation = "https://rust-embedded.github.io/cortex-m-rt/"
keywords = ["arm", "cortex-m", "runtime", "startup"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rt"
readme = "README.md"
repository = "https://github.com/rust-embedded/cortex-m-rt"
version = "0.6.5"
autoexamples = true

[dependencies]
r0 = "0.2.2"
cortex-m-rt-macros = { path = "macros", version = "0.1.3" }

[dev-dependencies]
cortex-m = "0.5.7"
panic-halt = "0.2.0"
cortex-m-semihosting = "0.3.1"

[dev-dependencies.rand]
default-features = false
version = "0.5.5"

[target.'cfg(not(target_os = "none"))'.dev-dependencies]
compiletest_rs = "0.3.14"

[[example]]
name = "device"
required-features = ["device"]

[features]
device = []
